feat: add exceptions
storipress/wordpress-sdk pull request #2
Opened 2023-12-10 11:42 UTC by Lyrisbee

## Purpose

Add Rest Exceptions
* term_exists
* duplicate_term_slug
* rest_cannot_create
* rest_cannot_update

2023-12-11 01:21 UTC, bepsvpt requested changes

2023-12-11 01:21 UTC, bepsvpt commented on src/Exceptions/Rest/RestHttpException.php
> +abstract class RestHttpException extends HttpException
為什麼會有 `Rest` 這個前綴？這樣是為了區分什麼呢？

2023-12-11 01:21 UTC, bepsvpt commented on src/Exceptions/Rest/TermExistsRestException.php
> +    public mixed $term_id;
`term_id` 除了 `int` 外，還會有什麼型態？

2023-12-11 01:21 UTC, bepsvpt commented on src/Requests/Request.php
>                  $response->body(),
除了型態不一樣外，`$payload` 不就是 `$response->body()` 嗎？這樣是不是傳了重複的資料到 `error` 這個函式？

2023-12-11 01:21 UTC, bepsvpt commented on src/Requests/Request.php
> +            403 => new BadRequestException($message, $status),
Bad Request 是 `403` 而不是 `401`？

2023-12-11 01:21 UTC, bepsvpt commented on src/Requests/Request.php
> +
這一行空行是？

2023-12-11 01:21 UTC, bepsvpt commented on src/Exceptions/Rest/TermExistsRestException.php
> +        $this->term_id = data_get($error->data, 'term_id');
`data_get` 的來源套件要確定有在 `composer.json`

2023-12-11 02:28 UTC, Lyrisbee commented on src/Requests/Request.php
> +            403 => new BadRequestException($message, $status),
噢噢 打錯了 400 bad request 403 forbidden

2023-12-11 03:05 UTC, Lyrisbee commented on src/Exceptions/Rest/RestHttpException.php
> +abstract class RestHttpException extends HttpException
這是指 /Rest 目錄就夠了，不用特別加 Rest 的前綴嗎

2023-12-11 03:12 UTC, Lyrisbee commented on src/Exceptions/Rest/TermExistsRestException.php
> +    public mixed $term_id;
int 或 null，term_id 在其他 exception 不一定存在，目前遇到的 term_exists 都存在，但不確定會不會有其他 case

2023-12-11 03:43 UTC, bepsvpt commented on src/Exceptions/Rest/RestHttpException.php
> +abstract class RestHttpException extends HttpException
> 這是指 /Rest 目錄就夠了

不是，以 `CannotUpdateException` 為例，為什麼會需要 `Rest` 在 class 名稱裡？這麼做的考量是什麼？

2023-12-11 03:44 UTC, bepsvpt commented on src/Exceptions/Rest/TermExistsRestException.php
> +    public mixed $term_id;
這樣不是應該用 `int|null` 嗎？

2023-12-11 03:45 UTC, Lyrisbee commented on src/Exceptions/Rest/RestHttpException.php
> +abstract class RestHttpException extends HttpException
是想說這樣就可以直接看出來這是 Rest API 的 Exception

2023-12-11 04:21 UTC, bepsvpt commented on src/Exceptions/Rest/RestHttpException.php
> +abstract class RestHttpException extends HttpException
這個套件除了呼叫 WordPress API 會產生 Exception 外，還有什麼其他可能會發生 Exception 的地方？

2023-12-11 05:18 UTC, Lyrisbee commented on src/Exceptions/Rest/RestHttpException.php
> +abstract class RestHttpException extends HttpException
沒有，但要符合 {code: string, message: string} 的格式才會認定是 rest api exception，其他都是 http exception，雖然還沒有遇到。還是這樣分是沒有意義的

2023-12-11 07:33 UTC, bepsvpt commented on src/Exceptions/Rest/RestHttpException.php
> +abstract class RestHttpException extends HttpException
假設我是一個開發者要用這個套件，我第一個疑惑就是為什麼有些 exception 在 `Rest` 底下，有些不是，這些 exceptions 是怎麼區別的，區別不是只名稱有 Rest 或 namespace 有 Rest，而是為什麼某個 exception 會被歸類在 Rest 底下，區分的即是什麼。

2023-12-12 04:17 UTC, bepsvpt requested changes

2023-12-12 04:17 UTC, bepsvpt commented on src/Objects/ErrorException.php
> +class ErrorException extends WordPressObject
`WordPressError`

2023-12-12 04:17 UTC, bepsvpt commented on src/Requests/Request.php
> +    protected function unexpectedValueException(string $message): UnexpectedValueException
message 看起來只有下面這兩種

- `Unexpected response value.`
- `Unexpected response format.`

這有什麼差別嗎？

2023-12-12 05:13 UTC, Lyrisbee commented on src/Requests/Request.php
> +    protected function unexpectedValueException(string $message): UnexpectedValueException
沒有太大的差別，都是回傳值不符合預期的值

2023-12-12 06:20 UTC, bepsvpt approved these changes

2023-12-12 06:35 UTC, merged