feat: add non pretty url
storipress/wordpress-sdk pull request #3
Opened 2023-12-11 01:20 UTC by Lyrisbee

## Purpose

use non pretty url when the wp-json route is invalid

2023-12-11 01:25 UTC, bepsvpt commented on src/Requests/Request.php
> +            if ((!($response instanceof Response) || $response->json() === null)) {
選擇在發生錯誤後重新嘗試 `rest_route` 的設計是考量什麼？沒有考慮都改用 `rest_route` 的原因是？

2023-12-11 02:51 UTC, Lyrisbee commented on src/Requests/Request.php
> +            if ((!($response instanceof Response) || $response->json() === null)) {
因為產生這個錯誤的使用者他用 rest_route 會有問題，反而 wp-json 是可以正常執行的，根據現在的錯誤 wp-json 在大部分使用者應該是沒問題的。 rest_route 加一層保險

2023-12-11 08:02 UTC, bepsvpt requested changes

2023-12-11 08:02 UTC, bepsvpt commented on src/Requests/Request.php
> +    public function getNonPrettyUrl(string $path): string
改在 `getUrl` 以第二個參數做切換

2023-12-11 08:02 UTC, bepsvpt commented on src/Requests/Request.php
> +            if ((!($response instanceof Response) || $response->json() === null)) {
現在這樣的寫法你認為有什麼問題存在？

2023-12-12 04:23 UTC, bepsvpt requested changes

2023-12-12 04:23 UTC, bepsvpt commented on src/Requests/GeneralRequest.php
>              ltrim($path, '/')
這個 `ltrim` 是正確的嗎？

2023-12-12 04:23 UTC, bepsvpt commented on src/Requests/GeneralRequest.php
> +        return sprintf('%s?rest_route=%s',
`?` 前面不需要 `/` 嗎？

2023-12-12 04:23 UTC, bepsvpt commented on src/Requests/GeneralRequest.php
> +                $basePath,
假設使用者沒調整，這 $basePath 預設會是 `wp-json`？如果是的話，`$prefix = 'wp-json'`

2023-12-12 04:23 UTC, bepsvpt commented on src/Requests/Request.php
> +            $options
排版

2023-12-12 04:23 UTC, bepsvpt commented on src/Requests/Request.php
> +            );
排版

2023-12-12 04:23 UTC, bepsvpt commented on src/Requests/GeneralRequest.php
> +                $basePath,
`bool $pretty = false`

2023-12-12 06:26 UTC, bepsvpt approved these changes
調整後可以直接 merge

2023-12-12 06:26 UTC, bepsvpt commented on src/Requests/Request.php
> +            $options
結尾 `,`，其他地方也檢查一下

2023-12-12 06:26 UTC, bepsvpt commented on src/Requests/GeneralRequest.php
> +    public function getUrl(string $path, string $basePath, bool $pretty): string
`$basePath` -> `$prefix` 另外一個檔案也一樣

2023-12-12 06:32 UTC, merged